# Generated by Django 4.2.7 on 2025-03-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gantt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.IntegerField()),
                ('nom_intervenant', models.CharField(max_length=255)),
                ('type_intervention', models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK RACC', 'NOK RACC'), ('NOK SAV', 'NOK SAV')], max_length=50, null=True)),
                ('heure_08', models.BooleanField(default=False)),
                ('heure_09', models.BooleanField(default=False)),
                ('heure_10', models.BooleanField(default=False)),
                ('heure_11', models.BooleanField(default=False)),
                ('heure_13', models.BooleanField(default=False)),
                ('heure_14', models.BooleanField(default=False)),
                ('heure_18', models.BooleanField(default=False)),
                ('taux_transfo', models.CharField(max_length=10)),
                ('taux_remplissage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StatistiquesGantt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('RACC', 'RACC'), ('SAV', 'SAV')], max_length=50)),
                ('taux_transfo', models.CharField(max_length=10)),
                ('nbr_inter_ok', models.IntegerField()),
                ('nbr_inter_nok', models.IntegerField()),
                ('nbr_inter_cours', models.IntegerField()),
                ('nbr_inter_peril', models.IntegerField()),
                ('nbr_inter_restant', models.IntegerField()),
                ('pdc_jour', models.IntegerField()),
                ('total', models.IntegerField()),
                ('taux_remplissage', models.CharField(max_length=10)),
                ('taux_avancement', models.CharField(max_length=10)),
                ('attention_controle', models.IntegerField(default=0)),
            ],
        ),
    ]
