# Generated by Django 5.1.6 on 2025-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARD2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton_commande', models.CharField(max_length=10, unique=True)),
                ('debut_intervention', models.DateTimeField()),
                ('fin_intervention', models.DateTimeField(blank=True, null=True)),
                ('terminee', models.BooleanField(default=False)),
                ('etat_intervention', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('technicien', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('pm', models.CharField(max_length=50)),
            ],
        ),
    ]
