# Generated by Django 5.1.6 on 2025-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlphoto',
            name='statut_pto',
            field=models.CharField(blank=True, choices=[('//', '//'), ('PTO et CAB absents', 'PTO et CAB absents'), ('première pose nécessaire', 'première pose nécessaire'), ('PTO a deplacer par confort et nouveau CAB a poser', 'PTO a deplacer par confort et nouveau CAB a poser'), ('PTO et CAB absent, premiere pose necessaire', 'PTO et CAB absent, premiere pose necessaire'), ('PTO mal positionné a déplacer et nouveau CAB a poser', 'PTO mal positionné a déplacer et nouveau CAB a pose'), ('PTO present et CAB non conforme a remplacer', 'PTO present et CAB non conforme a remplacer'), ('PTO a remetre en conformité et CAB conforme', 'PTO a remetre en conformité et CAB conforme'), ('PTO et CAB presents , conformes a remplacer', 'PTO et CAB presents , conformes a remplacer'), ('NE', 'NE'), ('Remsie en conformité', 'Remsie en conformité')], max_length=100, null=True),
        ),
    ]
