# Generated by Django 5.1.6 on 2025-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefracc',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='debriefracc',
            name='societe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Société'),
        ),
    ]
