# Generated by Django 5.1.6 on 2025-03-24 14:33

from django.db import migrations, models
from django.utils.timezone import now

def set_default_date_intervention(apps, schema_editor):
    Gantt = apps.get_model('core', 'Gantt')
    # Ici, vous pouvez définir une valeur par défaut pour tous les enregistrements existants.
    # Par exemple, vous pouvez utiliser la date actuelle ou une date fixe.
    default_date = now().date()  # ou par exemple: default_date = date(2025, 1, 1)
    for gantt in Gantt.objects.all():
        gantt.date_intervention = default_date
        gantt.save(update_fields=['date_intervention'])

class Migration(migrations.Migration):

    dependencies = [
        # Assurez-vous d'ajouter la dernière migration de votre app 'core'
        ('core', '0001_initial'),
    ]

    operations = [
        # Ajout du champ avec un temporaire default pour la migration
        migrations.AddField(
            model_name='gantt',
            name='date_intervention',
            field=models.DateField(default=now),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_date_intervention, migrations.RunPython.noop),
    ]
