# Generated by Django 5.1.6 on 2025-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relancejj',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro (récupéré via les paramètres)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='pec',
            field=models.CharField(blank=True, max_length=255, verbose_name='PEC (saisi manuellement)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='statut',
            field=models.CharField(blank=True, choices=[('Cloturée', 'Cloturée'), ('Taguée', 'Taguée')], max_length=20, verbose_name='Statut (calculé automatiquement)'),
        ),
    ]
