# Generated by Django 5.1.6 on 2025-03-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef_plateau', 'Chef de plateau'), ('manager', 'Manager'), ('agent', 'Agent'), ('technicien', 'Technicien'), ('direction', 'Direction')], default='agent', max_length=20),
        ),
    ]
