# Generated by Django 5.1.6 on 2025-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef_plateau', 'Chef de plateau'), ('manager', 'Manager'), ('agent', 'Agent'), ('technicien', 'Technicien'), ('direction', 'Direction'), ('user', 'Utilisateur')], default='user', max_length=20),
        ),
    ]
