# Generated by Django 5.1.6 on 2025-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_relancejj_numero_alter_relancejj_pec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grdv',
            name='jeton',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Jeton'),
        ),
    ]
