# Generated by Django 5.1.6 on 2025-03-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ard2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ard2',
            name='date_importation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
