# Generated by Django 5.1.6 on 2025-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_debriefracc_manager_debriefracc_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefsav',
            name='jeton_commande',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Jeton Commande'),
        ),
    ]
