# Generated by Django 5.1.6 on 2025-03-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250324_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gantt',
            name='date_intervention',
        ),
    ]
