# Generated by Django 5.1.6 on 2025-03-24 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gantt_date_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='date_intervention',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
