# Generated by Django 5.1.6 on 2025-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancejj',
            name='societe',
            field=models.CharField(blank=True, max_length=255, verbose_name='Société'),
        ),
    ]
