# Generated by Django 5.1.6 on 2025-04-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_debriefsav_jeton_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefsav',
            name='societe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Société'),
        ),
    ]
