# Generated by Django 5.1.6 on 2025-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grdv_jeton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relancejj',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure début (provenant de ARD2.debut_intervention)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure fin (provenant de ARD2.fin_intervention)'),
        ),
    ]
