# Generated by Django 5.1.6 on 2025-03-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ard2_date_importation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelanceJJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('activite', models.CharField(choices=[('SAV', 'SAV'), ('RACC', 'RACC')], max_length=4)),
                ('heure_prevue', models.TimeField()),
                ('techniciens', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=255)),
                ('pec', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('Cloturée', 'Cloturée'), ('Taguée', 'Taguée'), ('Relance démarrage', 'Relance démarrage'), ('Relance Cloture', 'Relance Cloture')], max_length=20)),
                ('jeton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='core.ard2')),
            ],
        ),
    ]
