# Generated by Django 5.1.6 on 2025-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_relancejj_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlphoto',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='controlphoto',
            name='societe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
