# Generated by Django 5.1.6 on 2025-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gantt_date_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='departement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='societe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
