# Generated by Django 5.1.6 on 2025-03-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_relancejj'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancejj',
            name='commentaire_cloture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='commentaire_demarrage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
