# Generated by Django 5.1.6 on 2025-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_relancejj_heure_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relancejj',
            name='jeton',
        ),
        migrations.AddField(
            model_name='relancejj',
            name='jeton_commande',
            field=models.CharField(blank=True, max_length=10, verbose_name='Jeton commande'),
        ),
    ]
