# Generated by Django 5.1.6 on 2025-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_debriefsav_appel_tech_debriefsav_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlphoto',
            name='agent2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='controlphoto',
            name='resultats_verification2',
            field=models.CharField(blank=True, choices=[('Validé', 'Validé'), ('Débrief modifié', 'Débrief modifié'), ('Non validé', 'Non validé')], max_length=50, null=True),
        ),
    ]
