# Generated by Django 5.1.6 on 2025-03-25 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gantt_departement_gantt_societe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('commentateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commentateur')),
                ('jeton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.relancejj', verbose_name='RelanceJJ associé')),
            ],
        ),
    ]
