# Generated by Django 5.1.6 on 2025-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_controlphoto_numero_controlphoto_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlphoto',
            name='statut_appel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
