# Generated by Django 5.1.6 on 2025-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_relancejj_commentaire_cloture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tech', models.CharField(max_length=50, unique=True, verbose_name='ID Technicien')),
                ('nom_tech', models.CharField(max_length=255, verbose_name='Nom du Technicien')),
                ('departement', models.CharField(max_length=255, verbose_name='Département')),
                ('log_free', models.CharField(max_length=255, verbose_name='Log Free')),
                ('competence', models.CharField(blank=True, choices=[('SAV', 'SAV'), ('', 'Vide')], max_length=3, verbose_name='Compétence')),
                ('actif_depuis', models.DateField(verbose_name='Actif depuis')),
                ('controle_photo', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2')], max_length=2, verbose_name='Contrôle Photo')),
                ('manager', models.CharField(max_length=255, verbose_name='Manager')),
                ('zone', models.CharField(choices=[('Zone 1', 'Zone 1'), ('Zone 2', 'Zone 2')], max_length=50, verbose_name='Zone')),
                ('grille_actif', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3, verbose_name='Grille Actif')),
                ('log_technicien', models.CharField(max_length=255, verbose_name='Log Technicien')),
                ('mdp', models.CharField(max_length=255, verbose_name='Mot de passe')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
