# Generated by Django 5.1.6 on 2025-03-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_relancejj_jeton_relancejj_jeton_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='log_technicien',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Log Technicien'),
        ),
        migrations.AlterField(
            model_name='parametres',
            name='mdp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe'),
        ),
    ]
