# Generated by Django 5.1.6 on 2025-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du commentaire'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='created_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure du commentaire'),
        ),
    ]
