# Generated by Django 5.1.6 on 2025-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parametres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('RACC', 'RACC'), ('SAV', 'SAV')], max_length=10, verbose_name="Type d'intervention")),
                ('taux_transfo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de transformation')),
                ('nbr_inter_cloturee_ok', models.IntegerField(verbose_name="Nombre d'interventions clôturées OK")),
                ('nbr_inter_cloturee_nok', models.IntegerField(verbose_name="Nombre d'interventions clôturées NOK")),
                ('nbr_inter_en_cours', models.IntegerField(verbose_name="Nombre d'interventions en cours")),
                ('nbr_inter_en_peril', models.IntegerField(verbose_name="Nombre d'interventions en péril")),
                ('nbr_inter_restant', models.IntegerField(verbose_name="Nombre d'interventions restantes")),
                ('pdc_du_jour', models.IntegerField(verbose_name='PDC du jour')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('taux_remplissage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de remplissage')),
                ('taux_avancement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'avancement")),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
        ),
        migrations.DeleteModel(
            name='StatistiquesGantt',
        ),
        migrations.AddField(
            model_name='gantt',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_08',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_09',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_10',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_11',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_13',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_14',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='heure_18',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='taux_remplissage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='taux_transfo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='type_intervention',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
    ]
