# Generated by Django 5.1.6 on 2025-03-31 16:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_controlphoto_statut_appel'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlphoto',
            name='jeton_fk',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='control_photos', to='core.relancejj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlphoto',
            name='jeton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
