# Generated by Django 5.1.6 on 2025-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parametres_log_technicien_alter_parametres_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='numero_technicien',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro du Technicien'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='societe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Société'),
        ),
    ]
