# Generated by Django 5.1.6 on 2025-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_controlphoto_agent2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancejj',
            name='synchro',
            field=models.CharField(blank=True, max_length=10, verbose_name='Statut de synchronisation (provenant de ARD2.etat_intervention)'),
        ),
        migrations.AlterField(
            model_name='parametres',
            name='grille_actif',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name='Grille Actif'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='activite',
            field=models.CharField(blank=True, choices=[('SAV', 'SAV'), ('RACC', 'RACC')], max_length=4, verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='departement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure début'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure fin'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_prevue',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure prévue'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='pec',
            field=models.CharField(blank=True, max_length=255, verbose_name='PEC'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='statut',
            field=models.CharField(blank=True, choices=[('Cloturée', 'Cloturée'), ('Taguée', 'Taguée')], max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='techniciens',
            field=models.CharField(blank=True, max_length=255, verbose_name='Techniciens'),
        ),
    ]
