# Generated by Django 5.1.6 on 2025-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ganttstatistics_delete_statistiquesgantt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(max_length=20)),
                ('date_rdv', models.DateField()),
                ('type_intervention', models.CharField(choices=[('Pose de PTO ZMD', 'Pose de PTO ZMD'), ('Pose de PTO ZTD', 'Pose de PTO ZTD'), ('SAV', 'SAV'), ('PON', 'PON'), ('Remise en conformité', 'Remise en conformité'), ('null', 'Null')], max_length=50)),
                ('question', models.CharField(choices=[('Appel CA ?', 'Appel CA ?'), ('Null', 'Null')], max_length=50)),
                ('reponse', models.CharField(choices=[('Non', 'Non'), ('Pas d’appel CA effectué', 'Pas d’appel CA effectué'), ('CA injoignable', 'CA injoignable'), ('Null', 'Null')], max_length=50)),
                ('reponse_libre', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_nom_prenom', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
