# Generated by Django 5.1.6 on 2025-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_relancejj_synchro_alter_parametres_grille_actif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gantt',
            name='type_intervention',
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_08',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_09',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_11',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_12',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_13',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_14',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_15',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_16',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_17',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='jeton_18',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gantt',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
