# Generated by Django 5.1.6 on 2025-03-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_controlphoto_jeton_fk_alter_controlphoto_jeton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlphoto',
            old_name='jeton_fk',
            new_name='jeton_relation',
        ),
    ]
