# Generated by Django 5.1.6 on 2025-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commentaire_created_date_commentaire_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='id_grdv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Grdv'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='nom_prenom_grdv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom prénom Grdv'),
        ),
    ]
