# Generated by Django 5.1.6 on 2025-03-31 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_jeton_fk_controlphoto_jeton_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlphoto',
            name='jeton_relation',
        ),
        migrations.AddField(
            model_name='controlphoto',
            name='jetonjj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controlphoto',
            name='jeton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_photos', to='core.relancejj'),
        ),
    ]
