# Generated by Django 5.1.6 on 2025-03-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('tech', models.CharField(max_length=255)),
                ('groupe_tech', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2')], max_length=2)),
                ('actif_depuis', models.DateField()),
                ('zone_manager', models.CharField(blank=True, choices=[('Zone1', 'Zone1'), ('Zone2', 'Zone2'), ('#N/A', '#N/A')], max_length=10, null=True)),
                ('statut', models.CharField(choices=[('Taguée', 'Taguée'), ('Cloturée', 'Cloturée')], max_length=20)),
                ('secteur', models.CharField(max_length=255)),
                ('statut_pto', models.CharField(blank=True, choices=[('//', '//'), ('PTO et CAB absents', 'PTO et CAB absents'), ('première pose nécessaire', 'première pose nécessaire')], max_length=50, null=True)),
                ('synchro', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3, null=True)),
                ('agent', models.CharField(max_length=255)),
                ('resultats_verification', models.CharField(blank=True, choices=[('Rectifié et validé', 'Rectifié et validé'), ('Non validé', 'Non validé')], max_length=50, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('jeton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_photos', to='core.relancejj')),
            ],
        ),
    ]
