# Generated by Django 5.1.6 on 2025-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_gantt_type_intervention_gantt_jeton_08_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ard2',
            name='date_rendez_vous',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
