# Generated by Django 5.1.6 on 2025-03-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_controlphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlafroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_a_froid', models.CharField(choices=[('Validé', 'Validé'), ('Non validé', 'Non validé'), ('null', 'null')], default='null', max_length=20, verbose_name='Résultat à froid')),
                ('commentaire', models.CharField(choices=[('PTO prise zoomer + decharge pto dans le placard / rectifié et validé', 'PTO prise zoomer + decharge pto dans le placard / rectifié et validé'), ('photo Mur avant travaux entamer / photo Mur après ne montre pas le PTO / REF PTO éronnée', 'photo Mur avant travaux entamer / photo Mur après ne montre pas le PTO / REF PTO éronnée'), ('null', 'null')], default='null', max_length=150, verbose_name='Commentaire')),
                ('control_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controlafroid', to='core.controlphoto')),
            ],
            options={
                'verbose_name': 'Control à froid',
                'verbose_name_plural': 'Controls à froid',
            },
        ),
    ]
