# Generated by Django 5.1.6 on 2025-03-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_controlafroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='heure_12',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_15',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_16',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_17',
            field=models.CharField(blank=True, choices=[('OK SAV', 'OK SAV'), ('OK RACC', 'OK RACC'), ('NOK SAV', 'NOK SAV'), ('NOK RACC', 'NOK RACC'), ('En cours SAV', 'En cours SAV'), ('En cours RACC', 'En cours RACC'), ('Alerte SAV', 'Alerte SAV'), ('Alerte RACC', 'Alerte RACC'), ('Planifiée SAV', 'Planifiée SAV'), ('Planifiée RACC', 'Planifiée RACC')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DebriefRACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('tech', models.CharField(max_length=255)),
                ('numero_technicien', models.CharField(max_length=50)),
                ('nouveaux_tech', models.DateField()),
                ('zone_manager', models.CharField(max_length=255)),
                ('code_cloture_technicien', models.TextField()),
                ('reference_pm', models.CharField(max_length=50)),
                ('appel_tech', models.CharField(choices=[("Pas d'appel", "Pas d'appel"), ('Appel à chaud', 'Appel à chaud'), ('null', 'null')], default='null', max_length=20)),
                ('synchro', models.CharField(choices=[('Echec', 'Echec'), ('Taguées', 'Taguées'), ('null', 'null')], default='null', max_length=20)),
                ('secteur', models.CharField(max_length=255)),
                ('type_echec', models.CharField(choices=[('Echec client', 'Echec client'), ("Echec d'acces", "Echec d'acces"), ('null', 'null')], default='null', max_length=20)),
                ('pec_par', models.CharField(max_length=255)),
                ('resultat_controle', models.CharField(choices=[('RAS', 'RAS'), ('null', 'null')], default='null', max_length=10)),
                ('diagnostic', models.TextField()),
                ('jeton', models.ForeignKey(limit_choices_to={'activite': 'RACC'}, on_delete=django.db.models.deletion.CASCADE, related_name='debrief_racc', to='core.relancejj')),
            ],
        ),
        migrations.CreateModel(
            name='DebriefSAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'intervention")),
                ('heure', models.TimeField(verbose_name="Heure d'intervention")),
                ('tech', models.CharField(max_length=255, verbose_name='Nom du technicien')),
                ('numero_tech', models.CharField(max_length=50, verbose_name='Numéro du technicien')),
                ('nouveaux_tech', models.DateField(blank=True, null=True, verbose_name='Nouveaux tech')),
                ('zone_manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zone/Manager')),
                ('code_cloture_tech', models.TextField(blank=True, null=True, verbose_name='Code clôture technicien')),
                ('reference_pm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence PM')),
                ('appel_tech', models.CharField(blank=True, choices=[("Pas d'appel", "Pas d'appel"), ('Appel à chaud', 'Appel à chaud'), (None, 'null')], max_length=20, null=True, verbose_name='Appel tech')),
                ('synchro', models.CharField(blank=True, choices=[('Echec', 'Echec'), ('Taguée', 'Taguée'), (None, 'null')], max_length=10, null=True, verbose_name='Synchro')),
                ('secteur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secteur')),
                ('type_echec', models.CharField(blank=True, choices=[('Echec client', 'Echec client'), ("Echec d'acces", "Echec d'acces"), (None, 'null')], max_length=20, null=True, verbose_name="Type d'échec")),
                ('pec_par', models.CharField(blank=True, max_length=255, null=True, verbose_name='PEC par')),
                ('resultat_controle', models.CharField(blank=True, choices=[('RAS', 'RAS'), (None, 'null')], max_length=10, null=True, verbose_name='Résultat du contrôle')),
                ('diagnostic', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('jeton', models.ForeignKey(limit_choices_to={'activite': 'SAV'}, on_delete=django.db.models.deletion.CASCADE, related_name='debriefs_sav', to='core.relancejj')),
            ],
        ),
    ]
