# Generated by Django 5.1.6 on 2025-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_importardlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_08',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_09',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_10',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_11',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_12',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_13',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_14',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_15',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_16',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_17',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_debut_18',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_08',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_09',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_10',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_11',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_12',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_13',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_14',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_15',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_16',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_17',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='heure_fin_18',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
