# Generated by Django 5.1.6 on 2025-04-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gantt_heure_debut_08_gantt_heure_debut_09_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='commentaire_08',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_09',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='commentaire_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_08',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_09',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gantt',
            name='motif_retard_18',
            field=models.TextField(blank=True, null=True),
        ),
    ]
