# Generated by Django 5.1.6 on 2025-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gantt_heure_12_gantt_heure_15_gantt_heure_16_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionsSAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jeton', models.CharField(max_length=100, unique=True, verbose_name='Numéro de jeton')),
                ('date_intervention', models.DateField(verbose_name="Date d'intervention")),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('techniciens_initial', models.CharField(max_length=100, verbose_name='Technicien initial')),
                ('techniciens_intervenant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technicien intervenant')),
                ('nbr_nok', models.IntegerField(default=0, verbose_name='Nombre de NOK')),
                ('nbr_ok', models.IntegerField(default=0, verbose_name='Nombre de OK')),
                ('total_interventions', models.IntegerField(default=0, verbose_name='Total des interventions')),
                ('ref_pm', models.CharField(max_length=100, verbose_name='Référence PM')),
                ('status_intervention', models.CharField(choices=[('2906', '2906 - Freebox Etape 2/3'), ('3705', "3705 - Pas d'accès au local PM"), ('OK', 'OK'), ('3510', '3510 - Tube / Fibre HS'), ('3204', '3204 - Véhicule sur chambre'), ('303', '303 - Abonné absent'), ('3902', '3902 - PM vandalisé'), ('3202', "3202 - Pas d'intervention nécessaire")], max_length=50, verbose_name="Statut de l'intervention")),
                ('secteur', models.CharField(max_length=10, verbose_name='Secteur')),
                ('secu', models.TextField(blank=True, null=True, verbose_name='Sécurité')),
                ('heure_demarrage', models.TimeField(blank=True, null=True, verbose_name='Heure de démarrage')),
                ('heure_cloture', models.TimeField(blank=True, null=True, verbose_name='Heure de clôture')),
                ('synchro', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK'), ('Null', 'Null')], max_length=10, null=True, verbose_name='Synchro')),
                ('resultat_jj', models.TextField(blank=True, null=True, verbose_name='Résultat JJ')),
            ],
            options={
                'verbose_name': 'Intervention SAV',
                'verbose_name_plural': 'Interventions SAV',
            },
        ),
    ]
