# Generated by Django 5.1.6 on 2025-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_debriefracc_appel_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlphoto',
            name='statut_pto',
            field=models.CharField(blank=True, choices=[('//', '//'), ('PTO et CAB absents', 'PTO et CAB absents'), ('Remise en conformité', 'Remise en conformité'), ('NE', 'NE'), ('PTO et CAB presents,conformes et exploitables', 'PTO et CAB presents,conformes et exploitables'), ('conformes a remplacer', 'conformes a remplacer'), ('PTO a remettre en conformité et CAB conforme', 'PTO a remettre en conformité et CAB conforme'), ('PTO present et CAB non conforme a remplacer', 'PTO present et CAB non conforme a remplacer'), ('PTO mal positionné a déplacer et nouveau CAB a poser', 'PTO mal positionné a déplacer et nouveau CAB a poser'), ('PTO et CAB absent', 'PTO et CAB absent'), ('première pose nécessaire', 'première pose nécessaire'), ('PTO a deplacer par confort et nouveau CAB a poser', 'PTO a deplacer par confort et nouveau CAB a poser')], max_length=100, null=True),
        ),
    ]
