# Generated by Django 5.1.6 on 2025-03-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_interventionsracc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField(verbose_name='Date et heure du rendez-vous')),
                ('debut', models.DateTimeField(verbose_name="Date et heure du début d'intervention")),
                ('fin', models.DateTimeField(verbose_name="Date et heure de fin d'intervention")),
                ('statut_rendez_vous', models.CharField(max_length=255, verbose_name='Statut du rendez-vous')),
                ('statut_grdv', models.CharField(max_length=255, verbose_name='Statut GRDV')),
                ('activite', models.CharField(max_length=255, verbose_name='Activité')),
                ('plp', models.CharField(max_length=255, verbose_name='PLP')),
                ('technicien', models.CharField(max_length=255, verbose_name='Technicien')),
                ('presta', models.CharField(max_length=255, verbose_name='Presta')),
                ('tel_contact', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('adresse_postale', models.CharField(max_length=255, verbose_name='Adresse postale')),
                ('ref_commande', models.CharField(max_length=255, verbose_name='Référence de commande')),
                ('nro', models.CharField(max_length=255, verbose_name='NRO')),
                ('pm', models.CharField(max_length=255, verbose_name='PM')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('residence', models.CharField(max_length=255, verbose_name='Résidence')),
                ('bat', models.CharField(max_length=255, verbose_name='Bâtiment')),
                ('esc', models.CharField(max_length=255, verbose_name='Escalier')),
                ('eta', models.CharField(max_length=255, verbose_name='Étage')),
                ('por', models.CharField(max_length=255, verbose_name='Porte')),
                ('pto', models.CharField(max_length=255, verbose_name='PTO')),
                ('id_client', models.CharField(max_length=255, verbose_name='ID Client')),
                ('technologement', models.CharField(max_length=255, verbose_name='Technologement')),
                ('operateurlogement', models.CharField(max_length=255, verbose_name='Opérateur logement')),
                ('typezone', models.CharField(max_length=255, verbose_name='Type de zone')),
                ('typetechno', models.CharField(max_length=255, verbose_name='Type de technologie')),
                ('secteur_infra', models.CharField(max_length=255, verbose_name='Secteur infrastructure')),
                ('typebatiment', models.CharField(max_length=255, verbose_name='Type de bâtiment')),
                ('typepoteau_edf', models.CharField(max_length=255, verbose_name='Type de poteau EDF')),
                ('typeclient', models.CharField(max_length=255, verbose_name='Type de client')),
                ('typebox', models.CharField(max_length=255, verbose_name='Type de box')),
                ('id_debrief_rdv', models.CharField(max_length=255, verbose_name='ID Débrief RDV')),
                ('debrief_rdv', models.TextField(verbose_name='Débrief RDV')),
                ('Adresse_PM', models.CharField(max_length=255, verbose_name='Adresse PM')),
                ('Connecteur_Free_PM', models.CharField(max_length=255, verbose_name='Connecteur Free PM')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date et heure d'import du fichier")),
            ],
            options={
                'verbose_name': 'GRDV',
                'verbose_name_plural': 'GRDVs',
            },
        ),
    ]
