# Generated by Django 5.1.6 on 2025-03-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancejj',
            name='grdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='core.grdv', verbose_name='GRDV associé'),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='jeton_id_field',
            field=models.CharField(blank=True, max_length=10, verbose_name='Jeton ID (copie de ARD2.jeton_commande)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='activite',
            field=models.CharField(blank=True, choices=[('SAV', 'SAV'), ('RACC', 'RACC')], max_length=4, verbose_name='Activité (calculée à partir de GRDV.activite)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='commentaire_cloture',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire clôture'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='commentaire_demarrage',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire démarrage'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='date_intervention',
            field=models.DateField(blank=True, null=True, verbose_name='Date intervention (provenant de GRDV.date_rdv)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='departement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Département (provenant de ARD2.departement)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure début (ARD2.debut_intervention)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure fin (ARD2.fin_intervention)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='heure_prevue',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure prévue (provenant de GRDV.debut)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='jeton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='core.ard2', verbose_name='Jeton (ARD2)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Numéro (récupéré via les paramètres)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='pec',
            field=models.CharField(max_length=255, verbose_name='PEC (saisi manuellement)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='statut',
            field=models.CharField(blank=True, choices=[('Cloturée', 'Cloturée'), ('Taguée', 'Taguée')], max_length=20, verbose_name='Statut (calculé automatiquement)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='techniciens',
            field=models.CharField(blank=True, max_length=255, verbose_name='Techniciens (provenant de ARD2.technicien)'),
        ),
    ]
