# Generated by Django 5.1.6 on 2025-04-22 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_controlphoto_statut_pto'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancejj',
            name='date_statut_retard',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de la prise de statut'),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='details_retard',
            field=models.TextField(blank=True, verbose_name='Détails sur le retard'),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='pec_retard_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Statuté par'),
        ),
        migrations.AddField(
            model_name='relancejj',
            name='type_statut_retard',
            field=models.CharField(blank=True, choices=[('Retard démarrage', 'Retard démarrage'), ('Retard clôture', 'Retard clôture'), ('Faux démarrage', 'Faux démarrage'), ('Arrivé en avance', 'Arrivé en avance')], max_length=30, verbose_name='Type de Statut de Retard'),
        ),
    ]
