# Generated by Django 5.1.6 on 2025-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_relancejj_grdv_relancejj_jeton_id_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debriefracc',
            name='appel_tech',
            field=models.CharField(blank=True, choices=[("Pas d'appel", "Pas d'appel"), ('Appel à chaud', 'Appel à chaud'), ('null', 'null')], default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='code_cloture_technicien',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='date',
            field=models.DateField(help_text="Date de début d'intervention de GRDV"),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='heure',
            field=models.TimeField(help_text="Heure de début d'intervention de GRDV"),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='nouveaux_tech',
            field=models.CharField(blank=True, help_text='Champ à saisir manuellement', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='numero_technicien',
            field=models.CharField(blank=True, help_text='Numéro provenant de Parametres (optionnel)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='pec_par',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='reference_pm',
            field=models.CharField(blank=True, help_text="Référence PM issue d'ARD2", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='resultat_controle',
            field=models.CharField(blank=True, choices=[('RAS', 'RAS'), ('null', 'null')], default='null', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='secteur',
            field=models.CharField(blank=True, help_text="Département d'ARD2", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='synchro',
            field=models.CharField(blank=True, choices=[('Echec', 'Echec'), ('Taguées', 'Taguées'), ('null', 'null')], default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='tech',
            field=models.CharField(help_text="Technicien provenant d'ARD2", max_length=255),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='type_echec',
            field=models.CharField(blank=True, choices=[('Echec client', 'Echec client'), ("Echec d'acces", "Echec d'acces"), ('null', 'null')], default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='zone_manager',
            field=models.CharField(blank=True, help_text='Zone Manager provenant de Parametres', max_length=255, null=True),
        ),
    ]
