# Generated by Django 5.1.6 on 2025-03-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_debriefracc_appel_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debriefracc',
            name='date',
            field=models.DateField(blank=True, help_text="Date de début d'intervention de GRDV", null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='diagnostic',
            field=models.TextField(blank=True, help_text='Diagnostic (optionnel)', null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='heure',
            field=models.TimeField(blank=True, help_text="Heure de début d'intervention de GRDV", null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='numero_technicien',
            field=models.CharField(blank=True, help_text='Numéro provenant de Paramètres (optionnel)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='pec_par',
            field=models.CharField(blank=True, help_text='PEC PAR (optionnel)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='tech',
            field=models.CharField(blank=True, help_text="Technicien provenant d'ARD2", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='zone_manager',
            field=models.CharField(blank=True, help_text='Zone manager provenant de Paramètres (optionnel)', max_length=255, null=True),
        ),
    ]
