# Generated by Django 5.1.6 on 2025-03-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_debriefracc_date_alter_debriefracc_diagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefracc',
            name='grdv',
            field=models.ForeignKey(blank=True, help_text="GRDV associé pour récupérer la date et l'heure de début d'intervention", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='core.grdv'),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='appel_tech',
            field=models.CharField(blank=True, choices=[("Pas d'appel", "Pas d'appel"), ('Appel à chaud', 'Appel à chaud'), ('null', 'null')], default='null', help_text='Appel tech (optionnel)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='code_cloture_technicien',
            field=models.TextField(blank=True, help_text='Code de clôture du technicien (optionnel)', null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='date',
            field=models.DateField(blank=True, help_text="Date de début d'intervention (provenant de GRDV.debut)", null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='heure',
            field=models.TimeField(blank=True, help_text="Heure de début d'intervention (provenant de GRDV.debut)", null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='jeton',
            field=models.ForeignKey(blank=True, help_text="Jeton provenant d'ARD2 (clé étrangère)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='core.ard2'),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='nouveaux_tech',
            field=models.CharField(blank=True, help_text='Champ saisi manuellement (varchar, optionnel)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='reference_pm',
            field=models.CharField(blank=True, help_text="PM (provenant d'ARD2.pm)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='resultat_controle',
            field=models.CharField(blank=True, choices=[('RAS', 'RAS'), ('null', 'null')], default='null', help_text='Résultat du contrôle (optionnel)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='secteur',
            field=models.CharField(blank=True, help_text="Département (provenant d'ARD2.departement)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='synchro',
            field=models.CharField(blank=True, choices=[('Echec', 'Echec'), ('Taguées', 'Taguées'), ('null', 'null')], default='null', help_text='Synchro (optionnel)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='tech',
            field=models.CharField(blank=True, help_text="Technicien (provenant d'ARD2.technicien)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='type_echec',
            field=models.CharField(blank=True, choices=[('Echec client', 'Echec client'), ("Echec d'acces", "Echec d'acces"), ('null', 'null')], default='null', help_text="Type d'échec (optionnel)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='zone_manager',
            field=models.CharField(blank=True, help_text='Zone manager issu de Paramètres (optionnel)', max_length=50, null=True),
        ),
    ]
