# Generated by Django 5.1.6 on 2025-03-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_debriefracc_grdv_alter_debriefracc_appel_tech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debriefracc',
            name='date',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='grdv',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='jeton',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='numero_technicien',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='reference_pm',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='debriefracc',
            name='zone_manager',
        ),
        migrations.AddField(
            model_name='debriefracc',
            name='parametre',
            field=models.ForeignKey(blank=True, help_text='Paramètres du technicien (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parametres'),
        ),
        migrations.AddField(
            model_name='debriefracc',
            name='relance',
            field=models.ForeignKey(blank=True, help_text="RelanceJJ associée (doit avoir activite='RACC' et éventuellement être terminée)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='core.relancejj'),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='code_cloture_technicien',
            field=models.TextField(blank=True, help_text='Code de clôture du technicien', null=True),
        ),
        migrations.AlterField(
            model_name='debriefracc',
            name='nouveaux_tech',
            field=models.CharField(blank=True, help_text='Champ saisi manuellement (nouveaux tech)', max_length=255, null=True),
        ),
    ]
