# Generated by Django 5.1.6 on 2025-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_debriefracc_date_remove_debriefracc_grdv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debriefracc',
            name='code_cloture_technicien',
            field=models.TextField(blank=True, help_text='Code de clôture du technicien (optionnel)', null=True),
        ),
    ]
