# Generated by Django 5.1.6 on 2025-03-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_debriefracc_code_cloture_technicien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debriefracc',
            name='parametre',
            field=models.ForeignKey(blank=True, help_text='Paramètres du technicien (pour numéro et zone, optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parametres'),
        ),
    ]
