# Generated by Django 5.1.6 on 2025-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_debriefracc_parametre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relancejj',
            name='date_intervention',
        ),
        migrations.RemoveField(
            model_name='relancejj',
            name='jeton_id_field',
        ),
        migrations.AddField(
            model_name='relancejj',
            name='date_rdv',
            field=models.DateField(blank=True, null=True, verbose_name='Date RDV (provenant de GRDV.date_rdv)'),
        ),
        migrations.AlterField(
            model_name='relancejj',
            name='statut',
            field=models.CharField(blank=True, choices=[('Cloturée', 'Cloturée'), ('Taguée', 'Taguée')], max_length=20, null=True, verbose_name='Statut (calculé automatiquement)'),
        ),
    ]
