# Generated by Django 5.1.6 on 2025-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_relancejj_date_intervention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ard2',
            name='debut_intervention',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
